# Model Settings
detector:
  model_name: "yolo/yolo26n.pt"
  confidence_threshold: 0.4 # Min confidence to consider a detection

feature_extractor:
  model_name: "mobilenet_v3_small"
  embedding_dim: 576 # For MobileNetV3-Small
  input_size: 224

# Registration Settings
registration:
  num_raw_captures: 4
  num_augmentations_per_image: 3 # Will generate 5 augmented versions per raw capture

# Recognition Settings
recognition:
  similarity_threshold_high: 0.8 # Above this, recognize the object
  similarity_threshold_low: 0.5 # Below this, consider it unknown
  max_objects: 3 # Maximum objects to detect and recognize

# Data Paths
paths:
  objects_database: 'data\objects_db.json'
  raw_images: 'data\raw_images'